include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # allow having TODOs in the code
    todo: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info
  exclude:
    - "flutter/**"
    - "android/**"
    - "lib/**.g.dart"
    - "lib/**.gen.dart"
    - "lib/**.freezed.dart"

linter:
  rules:
    ### ENABLED RULES ###
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_require_non_null_named_parameters: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true

    annotate_overrides: true

    avoid_bool_literals_in_conditional_expressions: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_escaping_inner_quotes: true
    avoid_init_to_null: true
    avoid_redundant_argument_values: true
    avoid_returning_null: true
    avoid_renaming_method_parameters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    avoid_types_on_closure_parameters: true

    omit_local_variable_types: true

    await_only_futures: true

    camel_case_extensions: true
    camel_case_types: true

    cancel_subscriptions: true

    # this is actually dont_cast_nullable_to_non_nullable
    cast_nullable_to_non_nullable: true
    control_flow_in_finally: true

    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true

    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true

    # // TODO(username): message, https://URL-to-issue.
    flutter_style_todos: true

    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    missing_whitespace_between_adjacent_strings: true
    no_duplicate_case_values: true

    non_constant_identifier_names: true
    no_leading_underscores_for_local_identifiers: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true

    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true

    recursive_getters: true
    sized_box_for_whitespace: true

    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

    type_init_formals: true

    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true

    use_key_in_widget_constructors: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true

    ### DISABLED RULES ###
    # Avoid type stuttering
    always_specify_types: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    avoid_positional_boolean_parameters: false

    depend_on_referenced_packages: false

    curly_braces_in_flow_control_structures: false

    constant_identifier_names: false